[linux_base]
platform = native
build_flags =
  -I variants/linux
  -I src
  -I /usr/include
  -I .pio/libdeps/linux_repeater/CayenneLPP/src
  -I .pio/libdeps/linux_repeater/ArduinoJson/src
  -I .pio/libdeps/linux_repeater/Crypto
  -I .pio/libdeps/linux_repeater/RadioLib/src
  -D LINUX_PLATFORM=1
  -D RADIOLIB_BUILD_WITHOUT_ARDUINO=1
  -D RADIOLIB_EEPROM_UNSUPPORTED=1
  -D RADIOLIB_STATIC_ONLY=1
  -include variants/linux/Arduino.h
  -std=c++17
  -lpthread
  -lgpiod
  -li2c
board_level = extra
lib_compat_mode = off

lib_deps =
  jgromes/RadioLib@7.4.0
  rweather/Crypto@0.4.0
  electroniccats/CayenneLPP@1.6.1

build_src_filter =
  +<../src>
  +<../variants/linux>
  -<../src/helpers/esp32/*.cpp>
  -<../src/helpers/nrf52/*.cpp>
  -<../src/helpers/stm32/*.cpp>
  -<../src/helpers/bridges/ESPNowBridge.cpp>
  -<../src/helpers/*/*Display.cpp>
  -<../src/helpers/AutoDiscoverRTCClock.cpp>
  -<../src/helpers/bridges/RS232Bridge.cpp>
  -<../src/helpers/ui/*.cpp>

[env:linux]
extends = linux_base
build_flags =
  ${linux_base.build_flags}
  !pkg-config --cflags --libs libbsd-overlay --silence-errors || :

[env:linux_repeater]
extends = linux_base
build_flags =
  ${linux_base.build_flags}
  -D RADIO_CLASS=LinuxSX1262
  -D WRAPPER_CLASS=LinuxSX1262Wrapper
  -D USE_CUSTOM_SX1262_WRAPPER=1
  -D SKIP_CONFIG_OVERWRITE=1
  -D MAX_NEIGHBOURS=100
  -D LORA_TX_POWER=22
  -D LORA_FREQ=869.618f
  -D LORA_BW=62.5f
  -D LORA_SF=8
  -D LORA_CR=8
  -D MESH_DEBUG=1

build_src_filter =
  ${linux_base.build_src_filter}
  +<../examples/simple_repeater>
  -<../examples/simple_repeater/UITask.cpp>

lib_deps =
  ${linux_base.lib_deps}
